### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/hello.agus#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Felicidades @agusrabadan , muy buen primer trabajo!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Tanto en el index.html como en el styles.css al final del código has dejado líneas vacías (de la 79 a la 92 en el .html y de la 91 a la 116 en el .css)
- En las etiquetas < div > has añadido clases como post, postheader, PostBody,... algunas escritas con mayúsculas, otras en minúsculas, otras usando camelCase, ... Es importante mantener la coherencia a la hora de la escritura de clases para evitar confusiones.

**Comment by agusrabadan** [comment]
Oido Edo, ya he modificado los errores, muchas gracias!

**Comment by EduardoHernandezGuzman** [comment]
¡Buen trabajo!
